#!/usr/bin/env python3
"""
Sends pipeline results to a customer via email with file attachments.

Usage:
    python3 poc/send-email.py \
        --to customer@example.com \
        --niche "Horror / Supernatural" \
        --output-dir submissions/processing/20260301-120000_horror_output

Uses env vars GMAIL_USER and GMAIL_APP_PASSWORD (set in crontab or bashrc).
"""

import argparse
import email.mime.application
import email.mime.multipart
import email.mime.text
import os
import smtplib
import sys


def build_email(to_addr, from_addr, niche, output_dir):
    """Build multipart email with attachments."""
    msg = email.mime.multipart.MIMEMultipart()
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg["Subject"] = f"Your Faceless AI Channel Package — {niche}"

    # Count what we're sending
    files = sorted(f for f in os.listdir(output_dir)
                   if os.path.isfile(os.path.join(output_dir, f))
                   and not f.startswith("."))

    body = f"""Hi there,

Your AI channel package for the "{niche}" niche is ready!

Here's what's attached:
"""
    for f in files:
        body += f"  - {f}\n"

    body += """
These files were generated by our multi-agent AI pipeline:
  Niche Research Agent -> Blueprint Architect -> Script Writer -> Review -> QA

What to do next:
  1. Review the niche research to confirm the opportunity
  2. Pick your favorite channel name from the blueprint
  3. Take any script and paste it into Pictory AI or InVideo
  4. Upload your first video!

Questions? Just reply to this email.

— The Pataray Pipeline
   Built by a creator, for creators.
"""

    msg.attach(email.mime.text.MIMEText(body, "plain"))

    # Attach all output files
    for filename in files:
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "rb") as f:
            att = email.mime.application.MIMEApplication(f.read())
            att.add_header("Content-Disposition", "attachment", filename=filename)
            msg.attach(att)

    return msg


def send(msg, user, password):
    """Send email via Gmail SMTP."""
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(user, password)
        server.send_message(msg)


def main():
    parser = argparse.ArgumentParser(description="Send pipeline results via email")
    parser.add_argument("--to", required=True, help="Recipient email")
    parser.add_argument("--niche", required=True, help="Niche name for subject line")
    parser.add_argument("--output-dir", required=True, help="Directory with output files")
    args = parser.parse_args()

    # Read credentials from environment
    gmail_user = os.environ.get("GMAIL_USER", "spataray@gmail.com")
    gmail_pass = os.environ.get("GMAIL_APP_PASSWORD")

    if not gmail_pass:
        print("ERROR: GMAIL_APP_PASSWORD env variable not set.")
        print("Set it in crontab or ~/.bashrc:")
        print('  export GMAIL_APP_PASSWORD="your-16-char-app-password"')
        sys.exit(1)

    if not os.path.isdir(args.output_dir):
        print(f"ERROR: Output directory not found: {args.output_dir}")
        sys.exit(1)

    print(f"Building email to {args.to}...")
    msg = build_email(args.to, gmail_user, args.niche, args.output_dir)

    print(f"Sending via smtp.gmail.com as {gmail_user}...")
    send(msg, gmail_user, gmail_pass)
    print("Email sent successfully.")


if __name__ == "__main__":
    main()
